name: Publish to GitHub Pages

on:
  push:
    branches:
      - Deploy
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          mkdir public
          cat > public/README.MD <<EOL
          GitHub Page 發佈分支
          EOL
          cat > public/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>Native.Framework</title>
            </head>
            <body>
              <p>Native.Framework</p><br><strong>${{ github.sha }}</strong>
            </body>
          </html>
          EOL
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
          keep_history: true
          fqdn: native.run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
